version: "3.3"

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - ${DATABASE_PORT}:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
